from datetime import datetime
from graph.state import CaseState


def generate_report(state: CaseState) -> str:
    """
    Renders the completed CaseState into a single explainable Markdown report.
    Pure formatting — no LLM calls, no parsing logic. Every agent's raw output
    is included so the full reasoning trail is auditable end to end.
    """
    sections = [
        _header(),
        _case_summary(state),
        _investigation_section(state),
        _precedent_section(state),
        _witness_section(state),
        _arguments_section(state),
        _jury_section(state),
        _judge_section(state),
        _footer(),
    ]
    return "\n\n".join(s for s in sections if s)


def _header() -> str:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    return f"# Courtroom AI — Case Report\n\n*Generated: {timestamp}*"


def _case_summary(state: CaseState) -> str:
    return f"## Case Description\n\n{state['case_description']}"


def _investigation_section(state: CaseState) -> str:
    return f"## Investigation Findings\n\n{state.get('investigation', 'Not available.')}"


def _precedent_section(state: CaseState) -> str:
    disclaimer = (
        "> **Note:** Legal precedents cited in this report are illustrative of "
        "legal principles and have not been independently verified against "
        "case law databases."
    )
    return (
        f"## Legal Precedent Research\n\n"
        f"{disclaimer}\n\n"
        f"{state.get('precedents', 'Not available.')}"
    )


def _witness_section(state: CaseState) -> str:
    examination = state.get("witness_examination", "")
    if not examination:
        return (
            "## Witness Examination\n\n"
            "Not triggered — the Investigator did not flag disputed testimony "
            "in this case."
        )
    return f"## Witness Examination\n\n{examination}"


def _arguments_section(state: CaseState) -> str:
    plaintiff = state.get("plaintiff_argument", "Not available.")
    defense = state.get("defense_argument", "Not available.")
    return (
        f"## Arguments\n\n"
        f"### Plaintiff's Counsel\n\n{plaintiff}\n\n"
        f"### Defense Counsel\n\n{defense}"
    )


def _jury_section(state: CaseState) -> str:
    votes = state.get("juror_votes", [])
    majority = state.get("jury_majority", "Not available.")

    summary_table = _deliberation_table(votes)

    juror_blocks = []
    for v in votes:
        changed = v["verdict"] != v.get("final_verdict")
        change_note = "*(verdict changed after hearing peers)*" if changed else ""
        block = (
            f"#### {v['persona']} ({v['juror_id']}){change_note}\n\n"
            f"- **Initial verdict:** {v['verdict']} (confidence {v.get('original_confidence', v['confidence'])}/10)\n"
            f"- **Final verdict:** {v.get('final_verdict') or v['verdict']} (confidence {v['confidence']}/10)\n\n"
            f"**Initial reasoning:** {v['reasoning']}\n\n"
            f"**Rebuttal after hearing peers:** {v.get('rebuttal') or 'No rebuttal recorded.'}"
        )
        juror_blocks.append(block)

    return (
        f"## Jury Deliberation\n\n"
        f"**Majority verdict:** {majority}\n\n"
        f"{summary_table}\n\n"
        + "\n\n".join(juror_blocks)
    )


def _deliberation_table(votes: list) -> str:
    """Renders a compact Markdown table showing each juror's vote before and after rebuttal."""
    if not votes:
        return ""

    rows = ["| Juror | Initial Verdict | Final Verdict | Confidence (before → after) | Changed? |",
            "|---|---|---|---|---|"]
    for v in votes:
        changed = v["verdict"] != v.get("final_verdict")
        rows.append(
            f"| {v['persona']} | {v['verdict']} | {v.get('final_verdict') or v['verdict']} | "
            f"{v.get('original_confidence', v['confidence'])} → {v['confidence']} | "
            f"{'Yes' if changed else '— No'} |"
        )
    return "\n".join(rows)


def _judge_section(state: CaseState) -> str:
    return f"## Judge's Ruling\n\n{state.get('judge_decision', 'Not available.')}"


def _footer() -> str:
    return (
        "---\n\n"
        "*This report was generated by a multi-agent AI system for "
        "demonstration purposes and does not constitute legal advice.*"
    )